run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - copyloopvar
    - gci
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - perfsprint
    - revive
    - testifylint
    - usestdlibvars
    - wastedassign

linters-settings:
  gosec:
    includes:
      - G102
      - G106
      - G108
      - G109
      - G111
      - G112
      - G201
      - G203
  perfsprint:
    err-error: true
    errorf: true
    int-conversion: true
    sprintf1: true
    strconcat: true
  testifylint:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
        - gosec 
    - linters:
        - structcheck
        - unused
      text: "`data` is unused"
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - revive
      text: "var-naming:"
    - linters:
        - revive
      text: "exported:"
